drop table if exists departments CASCADE;
drop table if exists worked_hours CASCADE;
drop table if exists workers CASCADE;


create table departments
(
    departments_id bigint generated by default as identity,
    name           varchar(255),
    primary key (departments_id)
);
create table worked_hours
(
    worked_hours_id bigint generated by default as identity,
    end_work        timestamp,
    start_work      timestamp,
    worker_id       bigint,
    primary key (worked_hours_id)
);
create table workers
(
    worker_id      bigint generated by default as identity,
    last_name      varchar(255),
    name           varchar(255),
    position       varchar(255),
    departments_id bigint,
    primary key (worker_id)
);

insert into worked_hours(worked_hours_id,start_work,end_work,worker_id)
values (null ,'2021-07-02T19:17:12.936','2021-07-02T19:17:12.936',1),
   (null ,'2021-07-02T19:17:12.936','2021-07-02T19:17:12.936',2),
    (null ,'2021-07-02T19:17:12.33','2021-07-02T19:17:12.936',1);


insert into departments(departments_id,name)
values ( null,'MANNNNNNUTDDDD');

insert into workers(worker_id, name, last_name, position, departments_id)
values (null, 'Oleg', 'tereshkov', 'Developer', 1);

insert into workers(worker_id, name, last_name, position, departments_id)
values (null, 'OLLLL', 'OLLLLL', '2016-12-09T09:00:00Z', 1);



alter table worked_hours
    add constraint FKbnra0tx979gf3djno842cigu foreign key (worker_id) references workers;
alter table workers
    add constraint FKlfw269eirt3xonxkhnbmvsa3g foreign key (departments_id) references departments;