drop table if exists departments CASCADE;
drop table if exists worked_hours CASCADE;
drop table if exists workers CASCADE;
drop table if exists warkers_department CASCADE;


create table warkers_department
(
    departments_id bigint,
    worker_id      bigint not null,
    primary key (worker_id)
);

create table departments
(
    departments_id bigint generated by default as identity,
    name           varchar(255),
    primary key (departments_id)
);

create table workers
(
    worker_id bigint generated by default as identity,
    last_name varchar(255),
    name      varchar(255),
    position  varchar(255),
    primary key (worker_id)
);

create table worked_hours
(
    worked_hours_id bigint generated by default as identity,
    end_work        timestamp,
    start_work      timestamp,
    worker_id       bigint,
    primary key (worked_hours_id)

) ;

insert into departments(departments_id, name)
values (null, 'MMMMMMMMMM'),
(null ,'dsdcsdcsdc');

insert into warkers_department(departments_id, worker_id)
values (1, 1),
       (2, 2);

insert into worked_hours(worked_hours_id, end_work, start_work,worker_id)
values (null, '2021-07-02T19:17:12.936', '2021-07-02T19:17:12.936',1),
       (null, '2021-07-02T19:17:12.936', '2021-07-02T19:17:12.936',2),
       (null, '2021-07-02T19:17:12.33', '2021-07-02T19:17:12.936',1);


insert into workers(worker_id, name, last_name, position)
values (null, 'Oleg', 'tereshkov', 'Developer');

insert into workers(worker_id, name, last_name, position)
values (null, 'OLLLL', 'OLLLLL', '2016-12-09T09:00:00Z');


alter table warkers_department
    add constraint FK9l8jouusekypd07sepy19uqcl foreign key (departments_id) references departments;
alter table warkers_department
    add constraint FKq5759qwm37s9frs44st7w4nk6 foreign key (worker_id) references workers;
alter table worked_hours
    add constraint FKbnra0tx979gf3djno842cigu foreign key (worker_id) references workers;




--  drop table if exists departments CASCADE;
-- drop table if exists warkers_department CASCADE;
-- drop table if exists warkers_time CASCADE;
--     drop table if exists worked_hours CASCADE;
--     drop table if exists workers CASCADE;
--     create table departments (departments_id bigint generated by default as identity, name varchar(255), primary key (departments_id));
--      create table warkers_department (departments_id bigint, worker_id bigint not null, primary key (worker_id));
--      create table warkers_time (worker_id bigint, worked_hours_id bigint not null, primary key (worked_hours_id));
--     create table worked_hours (worked_hours_id bigint generated by default as identity, end_work timestamp, start_work timestamp, primary key (worked_hours_id));
--    create table workers (worker_id bigint generated by default as identity, last_name varchar(255), name varchar(255), position varchar(255), primary key (worker_id));
--
-- insert into departments(departments_id, name)
-- values (null, 'MMMMMMMMMM'),
-- (null ,'dsdcsdcsdc');
--
-- insert into warkers_department(departments_id, worker_id)
-- values (1, 1),
--        (2, 2);
--
--
-- insert into warkers_time(worker_id, worked_hours_id)
-- values (1, 1),
--        (2, 2),
-- (1,2);
--
-- insert into worked_hours(worked_hours_id, end_work, start_work)
-- values (null, '2021-07-02T19:17:12.936', '2021-07-02T19:17:12.936'),
--        (null, '2021-07-02T19:17:12.936', '2021-07-02T19:17:12.936'),
--        (null, '2021-07-02T19:17:12.33', '2021-07-02T19:17:12.936');
--
-- insert into workers(worker_id, name, last_name, position)
-- values (null, 'Oleg', 'tereshkov', 'Developer');
--
-- insert into workers(worker_id, name, last_name, position)
-- values (null, 'OLLLL', 'OLLLLL', '2016-12-09T09:00:00Z');
--
--    alter table warkers_department add constraint FK9l8jouusekypd07sepy19uqcl foreign key (departments_id) references departments;
--   alter table warkers_department add constraint FKq5759qwm37s9frs44st7w4nk6 foreign key (worker_id) references workers;
--   alter table warkers_time add constraint FK8ky4ue2871x2353ieisg309k foreign key (worker_id) references workers;
--      alter table warkers_time add constraint FKocpyx2a8m3ma9orqr8732s107 foreign key (worked_hours_id) references worked_hours;